[package]
name = "open-farming-hackdays-label-creator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
dioxus = { version = "0.6", features = ["web"] }
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.38"
web-sys = { version = "0.3.70", features = ["Navigator", "Clipboard"] }
serde_qs = "0.13.0"
wasm-bindgen = "0.2"
strum = "0.26.3"
strum_macros = "0.26.4"
rust-i18n = "3.1.2"
markdown = "1.0.0-alpha.22"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[package.metadata.i18n]
# The available locales for your application, default: ["en"].
available-locales = ["de-CH"]

# The default locale, default: "en".
default-locale = "de-CH"

# Path for your translations YAML file, default: "locales".
# This config for let `cargo i18n` command line tool know where to find your translations.
# You must keep this path same as the one you pass to method `rust_i18n::i18n!`.
load-path = "locales"
