[package]
name = "open-farming-hackdays-label-creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
dioxus = { version = "0.5", features = ["web"] }
manganis = "0.2.2"
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
