[package]
name = "open-farming-hackdays-label-creator"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
dioxus = { version = "0.6", features = ["web"] }
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.38"
web-sys = { version = "0.3.70", features = ["Navigator", "Clipboard"] }
serde_qs = "0.13.0"
wasm-bindgen = "0.2"
strum = "0.26.3"
strum_macros = "0.26.4"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
