use serde::{Deserialize, Serialize};

#[derive(PartialEq, Serialize, Deserialize, Clone, Debug)]
pub enum Country {
    CH,
    EU,
    NoOriginRequired,
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    YE,
    YT,
    ZA,
    ZM,
    ZW,
}

impl Country {
    pub fn display_name(&self) -> &'static str {
        match self {
            Country::CH => "Schweiz",
            Country::EU => "EU",
            Country::NoOriginRequired => "Keine Herkunftsangabe benötigt",
            Country::AD => "Andorra",
            Country::AE => "Vereinigte Arabische Emirate",
            Country::AF => "Afghanistan",
            Country::AG => "Antigua und Barbuda",
            Country::AI => "Anguilla",
            Country::AL => "Albanien",
            Country::AM => "Armenien",
            Country::AO => "Angola",
            Country::AQ => "Antarktis",
            Country::AR => "Argentinien",
            Country::AS => "Amerikanisch-Samoa",
            Country::AT => "Österreich",
            Country::AU => "Australien",
            Country::AW => "Aruba",
            Country::AX => "Åland",
            Country::AZ => "Aserbaidschan",
            Country::BA => "Bosnien und Herzegowina",
            Country::BB => "Barbados",
            Country::BD => "Bangladesch",
            Country::BE => "Belgien",
            Country::BF => "Burkina Faso",
            Country::BG => "Bulgarien",
            Country::BH => "Bahrain",
            Country::BI => "Burundi",
            Country::BJ => "Benin",
            Country::BL => "Saint-Barthélemy",
            Country::BM => "Bermuda",
            Country::BN => "Brunei",
            Country::BO => "Bolivien",
            Country::BQ => "Bonaire, Sint Eustatius und Saba",
            Country::BR => "Brasilien",
            Country::BS => "Bahamas",
            Country::BT => "Bhutan",
            Country::BV => "Bouvetinsel",
            Country::BW => "Botswana",
            Country::BY => "Belarus",
            Country::BZ => "Belize",
            Country::CA => "Kanada",
            Country::CC => "Kokosinseln",
            Country::CD => "Demokratische Republik Kongo",
            Country::CF => "Zentralafrikanische Republik",
            Country::CG => "Republik Kongo",
            Country::CI => "Elfenbeinküste",
            Country::CK => "Cookinseln",
            Country::CL => "Chile",
            Country::CM => "Kamerun",
            Country::CN => "China",
            Country::CO => "Kolumbien",
            Country::CR => "Costa Rica",
            Country::CU => "Kuba",
            Country::CV => "Kap Verde",
            Country::CW => "Curaçao",
            Country::CX => "Weihnachtsinsel",
            Country::CY => "Zypern",
            Country::CZ => "Tschechien",
            Country::DE => "Deutschland",
            Country::DJ => "Dschibuti",
            Country::DK => "Dänemark",
            Country::DM => "Dominica",
            Country::DO => "Dominikanische Republik",
            Country::DZ => "Algerien",
            Country::EC => "Ecuador",
            Country::EE => "Estland",
            Country::EG => "Ägypten",
            Country::EH => "Westsahara",
            Country::ER => "Eritrea",
            Country::ES => "Spanien",
            Country::ET => "Äthiopien",
            Country::FI => "Finnland",
            Country::FJ => "Fidschi",
            Country::FK => "Falklandinseln",
            Country::FM => "Mikronesien",
            Country::FO => "Färöer",
            Country::FR => "Frankreich",
            Country::GA => "Gabun",
            Country::GB => "Vereinigtes Königreich",
            Country::GD => "Grenada",
            Country::GE => "Georgien",
            Country::GF => "Französisch-Guayana",
            Country::GG => "Guernsey",
            Country::GH => "Ghana",
            Country::GI => "Gibraltar",
            Country::GL => "Grönland",
            Country::GM => "Gambia",
            Country::GN => "Guinea",
            Country::GP => "Guadeloupe",
            Country::GQ => "Äquatorialguinea",
            Country::GR => "Griechenland",
            Country::GS => "Südgeorgien und die Südlichen Sandwichinseln",
            Country::GT => "Guatemala",
            Country::GU => "Guam",
            Country::GW => "Guinea-Bissau",
            Country::GY => "Guyana",
            Country::HK => "Hongkong",
            Country::HM => "Heard und McDonaldinseln",
            Country::HN => "Honduras",
            Country::HR => "Kroatien",
            Country::HT => "Haiti",
            Country::HU => "Ungarn",
            Country::ID => "Indonesien",
            Country::IE => "Irland",
            Country::IL => "Israel",
            Country::IM => "Isle of Man",
            Country::IN => "Indien",
            Country::IO => "Britisches Territorium im Indischen Ozean",
            Country::IQ => "Irak",
            Country::IR => "Iran",
            Country::IS => "Island",
            Country::IT => "Italien",
            Country::JE => "Jersey",
            Country::JM => "Jamaika",
            Country::JO => "Jordanien",
            Country::JP => "Japan",
            Country::KE => "Kenia",
            Country::KG => "Kirgisistan",
            Country::KH => "Kambodscha",
            Country::KI => "Kiribati",
            Country::KM => "Komoren",
            Country::KN => "St. Kitts und Nevis",
            Country::KP => "Nordkorea",
            Country::KR => "Südkorea",
            Country::KW => "Kuwait",
            Country::KY => "Kaimaninseln",
            Country::KZ => "Kasachstan",
            Country::LA => "Laos",
            Country::LB => "Libanon",
            Country::LC => "St. Lucia",
            Country::LI => "Liechtenstein",
            Country::LK => "Sri Lanka",
            Country::LR => "Liberia",
            Country::LS => "Lesotho",
            Country::LT => "Litauen",
            Country::LU => "Luxemburg",
            Country::LV => "Lettland",
            Country::LY => "Libyen",
            Country::MA => "Marokko",
            Country::MC => "Monaco",
            Country::MD => "Moldau",
            Country::ME => "Montenegro",
            Country::MF => "Saint-Martin",
            Country::MG => "Madagaskar",
            Country::MH => "Marshallinseln",
            Country::MK => "Nordmazedonien",
            Country::ML => "Mali",
            Country::MM => "Myanmar",
            Country::MN => "Mongolei",
            Country::MO => "Macau",
            Country::MP => "Nördliche Marianen",
            Country::MQ => "Martinique",
            Country::MR => "Mauretanien",
            Country::MS => "Montserrat",
            Country::MT => "Malta",
            Country::MU => "Mauritius",
            Country::MV => "Malediven",
            Country::MW => "Malawi",
            Country::MX => "Mexiko",
            Country::MY => "Malaysia",
            Country::MZ => "Mosambik",
            Country::NA => "Namibia",
            Country::NC => "Neukaledonien",
            Country::NE => "Niger",
            Country::NF => "Norfolkinsel",
            Country::NG => "Nigeria",
            Country::NI => "Nicaragua",
            Country::NL => "Niederlande",
            Country::NO => "Norwegen",
            Country::NP => "Nepal",
            Country::NR => "Nauru",
            Country::NU => "Niue",
            Country::NZ => "Neuseeland",
            Country::OM => "Oman",
            Country::PA => "Panama",
            Country::PE => "Peru",
            Country::PF => "Französisch-Polynesien",
            Country::PG => "Papua-Neuguinea",
            Country::PH => "Philippinen",
            Country::PK => "Pakistan",
            Country::PL => "Polen",
            Country::PM => "Saint-Pierre und Miquelon",
            Country::PN => "Pitcairninseln",
            Country::PR => "Puerto Rico",
            Country::PS => "Palästina",
            Country::PT => "Portugal",
            Country::PW => "Palau",
            Country::PY => "Paraguay",
            Country::QA => "Katar",
            Country::RE => "Réunion",
            Country::RO => "Rumänien",
            Country::RS => "Serbien",
            Country::RU => "Russland",
            Country::RW => "Ruanda",
            Country::SA => "Saudi-Arabien",
            Country::SB => "Salomonen",
            Country::SC => "Seychellen",
            Country::SD => "Sudan",
            Country::SE => "Schweden",
            Country::SG => "Singapur",
            Country::SH => "St. Helena",
            Country::SI => "Slowenien",
            Country::SJ => "Svalbard und Jan Mayen",
            Country::SK => "Slowakei",
            Country::SL => "Sierra Leone",
            Country::SM => "San Marino",
            Country::SN => "Senegal",
            Country::SO => "Somalia",
            Country::SR => "Suriname",
            Country::SS => "Südsudan",
            Country::ST => "São Tomé und Príncipe",
            Country::SV => "El Salvador",
            Country::SX => "Sint Maarten",
            Country::SY => "Syrien",
            Country::SZ => "Eswatini",
            Country::TC => "Turks- und Caicosinseln",
            Country::TD => "Tschad",
            Country::TF => "Französische Süd- und Antarktisgebiete",
            Country::TG => "Togo",
            Country::TH => "Thailand",
            Country::TJ => "Tadschikistan",
            Country::TK => "Tokelau",
            Country::TL => "Osttimor",
            Country::TM => "Turkmenistan",
            Country::TN => "Tunesien",
            Country::TO => "Tonga",
            Country::TR => "Türkei",
            Country::TT => "Trinidad und Tobago",
            Country::TV => "Tuvalu",
            Country::TW => "Taiwan",
            Country::TZ => "Tansania",
            Country::UA => "Ukraine",
            Country::UG => "Uganda",
            Country::UM => "Amerikanische Überseeinseln",
            Country::US => "Vereinigte Staaten",
            Country::UY => "Uruguay",
            Country::UZ => "Usbekistan",
            Country::VA => "Vatikanstadt",
            Country::VC => "St. Vincent und die Grenadinen",
            Country::VE => "Venezuela",
            Country::VG => "Britische Jungferninseln",
            Country::VI => "Amerikanische Jungferninseln",
            Country::VN => "Vietnam",
            Country::VU => "Vanuatu",
            Country::WF => "Wallis und Futuna",
            Country::WS => "Samoa",
            Country::YE => "Jemen",
            Country::YT => "Mayotte",
            Country::ZA => "Südafrika",
            Country::ZM => "Sambia",
            Country::ZW => "Simbabwe",
        }
    }

    pub fn country_code(&self) -> &'static str {
        match self {
            Country::CH => "CH",
            Country::EU => "EU",
            Country::NoOriginRequired => "",
            Country::AD => "AD",
            Country::AE => "AE",
            Country::AF => "AF",
            Country::AG => "AG",
            Country::AI => "AI",
            Country::AL => "AL",
            Country::AM => "AM",
            Country::AO => "AO",
            Country::AQ => "AQ",
            Country::AR => "AR",
            Country::AS => "AS",
            Country::AT => "AT",
            Country::AU => "AU",
            Country::AW => "AW",
            Country::AX => "AX",
            Country::AZ => "AZ",
            Country::BA => "BA",
            Country::BB => "BB",
            Country::BD => "BD",
            Country::BE => "BE",
            Country::BF => "BF",
            Country::BG => "BG",
            Country::BH => "BH",
            Country::BI => "BI",
            Country::BJ => "BJ",
            Country::BL => "BL",
            Country::BM => "BM",
            Country::BN => "BN",
            Country::BO => "BO",
            Country::BQ => "BQ",
            Country::BR => "BR",
            Country::BS => "BS",
            Country::BT => "BT",
            Country::BV => "BV",
            Country::BW => "BW",
            Country::BY => "BY",
            Country::BZ => "BZ",
            Country::CA => "CA",
            Country::CC => "CC",
            Country::CD => "CD",
            Country::CF => "CF",
            Country::CG => "CG",
            Country::CI => "CI",
            Country::CK => "CK",
            Country::CL => "CL",
            Country::CM => "CM",
            Country::CN => "CN",
            Country::CO => "CO",
            Country::CR => "CR",
            Country::CU => "CU",
            Country::CV => "CV",
            Country::CW => "CW",
            Country::CX => "CX",
            Country::CY => "CY",
            Country::CZ => "CZ",
            Country::DE => "DE",
            Country::DJ => "DJ",
            Country::DK => "DK",
            Country::DM => "DM",
            Country::DO => "DO",
            Country::DZ => "DZ",
            Country::EC => "EC",
            Country::EE => "EE",
            Country::EG => "EG",
            Country::EH => "EH",
            Country::ER => "ER",
            Country::ES => "ES",
            Country::ET => "ET",
            Country::FI => "FI",
            Country::FJ => "FJ",
            Country::FK => "FK",
            Country::FM => "FM",
            Country::FO => "FO",
            Country::FR => "FR",
            Country::GA => "GA",
            Country::GB => "GB",
            Country::GD => "GD",
            Country::GE => "GE",
            Country::GF => "GF",
            Country::GG => "GG",
            Country::GH => "GH",
            Country::GI => "GI",
            Country::GL => "GL",
            Country::GM => "GM",
            Country::GN => "GN",
            Country::GP => "GP",
            Country::GQ => "GQ",
            Country::GR => "GR",
            Country::GS => "GS",
            Country::GT => "GT",
            Country::GU => "GU",
            Country::GW => "GW",
            Country::GY => "GY",
            Country::HK => "HK",
            Country::HM => "HM",
            Country::HN => "HN",
            Country::HR => "HR",
            Country::HT => "HT",
            Country::HU => "HU",
            Country::ID => "ID",
            Country::IE => "IE",
            Country::IL => "IL",
            Country::IM => "IM",
            Country::IN => "IN",
            Country::IO => "IO",
            Country::IQ => "IQ",
            Country::IR => "IR",
            Country::IS => "IS",
            Country::IT => "IT",
            Country::JE => "JE",
            Country::JM => "JM",
            Country::JO => "JO",
            Country::JP => "JP",
            Country::KE => "KE",
            Country::KG => "KG",
            Country::KH => "KH",
            Country::KI => "KI",
            Country::KM => "KM",
            Country::KN => "KN",
            Country::KP => "KP",
            Country::KR => "KR",
            Country::KW => "KW",
            Country::KY => "KY",
            Country::KZ => "KZ",
            Country::LA => "LA",
            Country::LB => "LB",
            Country::LC => "LC",
            Country::LI => "LI",
            Country::LK => "LK",
            Country::LR => "LR",
            Country::LS => "LS",
            Country::LT => "LT",
            Country::LU => "LU",
            Country::LV => "LV",
            Country::LY => "LY",
            Country::MA => "MA",
            Country::MC => "MC",
            Country::MD => "MD",
            Country::ME => "ME",
            Country::MF => "MF",
            Country::MG => "MG",
            Country::MH => "MH",
            Country::MK => "MK",
            Country::ML => "ML",
            Country::MM => "MM",
            Country::MN => "MN",
            Country::MO => "MO",
            Country::MP => "MP",
            Country::MQ => "MQ",
            Country::MR => "MR",
            Country::MS => "MS",
            Country::MT => "MT",
            Country::MU => "MU",
            Country::MV => "MV",
            Country::MW => "MW",
            Country::MX => "MX",
            Country::MY => "MY",
            Country::MZ => "MZ",
            Country::NA => "NA",
            Country::NC => "NC",
            Country::NE => "NE",
            Country::NF => "NF",
            Country::NG => "NG",
            Country::NI => "NI",
            Country::NL => "NL",
            Country::NO => "NO",
            Country::NP => "NP",
            Country::NR => "NR",
            Country::NU => "NU",
            Country::NZ => "NZ",
            Country::OM => "OM",
            Country::PA => "PA",
            Country::PE => "PE",
            Country::PF => "PF",
            Country::PG => "PG",
            Country::PH => "PH",
            Country::PK => "PK",
            Country::PL => "PL",
            Country::PM => "PM",
            Country::PN => "PN",
            Country::PR => "PR",
            Country::PS => "PS",
            Country::PT => "PT",
            Country::PW => "PW",
            Country::PY => "PY",
            Country::QA => "QA",
            Country::RE => "RE",
            Country::RO => "RO",
            Country::RS => "RS",
            Country::RU => "RU",
            Country::RW => "RW",
            Country::SA => "SA",
            Country::SB => "SB",
            Country::SC => "SC",
            Country::SD => "SD",
            Country::SE => "SE",
            Country::SG => "SG",
            Country::SH => "SH",
            Country::SI => "SI",
            Country::SJ => "SJ",
            Country::SK => "SK",
            Country::SL => "SL",
            Country::SM => "SM",
            Country::SN => "SN",
            Country::SO => "SO",
            Country::SR => "SR",
            Country::SS => "SS",
            Country::ST => "ST",
            Country::SV => "SV",
            Country::SX => "SX",
            Country::SY => "SY",
            Country::SZ => "SZ",
            Country::TC => "TC",
            Country::TD => "TD",
            Country::TF => "TF",
            Country::TG => "TG",
            Country::TH => "TH",
            Country::TJ => "TJ",
            Country::TK => "TK",
            Country::TL => "TL",
            Country::TM => "TM",
            Country::TN => "TN",
            Country::TO => "TO",
            Country::TR => "TR",
            Country::TT => "TT",
            Country::TV => "TV",
            Country::TW => "TW",
            Country::TZ => "TZ",
            Country::UA => "UA",
            Country::UG => "UG",
            Country::UM => "UM",
            Country::US => "US",
            Country::UY => "UY",
            Country::UZ => "UZ",
            Country::VA => "VA",
            Country::VC => "VC",
            Country::VE => "VE",
            Country::VG => "VG",
            Country::VI => "VI",
            Country::VN => "VN",
            Country::VU => "VU",
            Country::WF => "WF",
            Country::WS => "WS",
            Country::YE => "YE",
            Country::YT => "YT",
            Country::ZA => "ZA",
            Country::ZM => "ZM",
            Country::ZW => "ZW",
        }
    }
}

pub fn lookup_allergen(name: &str) -> bool {
    let mut is_allergen = false;
    for entry in food_db() {
        if entry.0.as_str() == name && entry.1 {
            is_allergen = true;
        }
    }
    is_allergen
}

pub fn food_db() -> Vec<(String, bool)> {
    let mut db: Vec<(String, bool)> = Vec::new();
    let db_csv = include_str!("food_db.csv");
    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_reader(db_csv.as_bytes());

    for record in rdr.records() {
        let record = record.unwrap();
        db.push((record.get(0).unwrap().to_string(), {
            record.get(1).unwrap().eq("1")
        }));
    }

    db
}

pub fn food_db_full() -> Vec<(String, bool, bool)> {
    let mut db: Vec<(String, bool, bool)> = Vec::new();
    let db_csv = include_str!("food_db.csv");
    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_reader(db_csv.as_bytes());

    for record in rdr.records() {
        let record = record.unwrap();
        let name = record.get(0).unwrap().to_string();
        let is_allergen = record.get(1).unwrap().eq("1");
        let is_agricultural = record.get(2).unwrap().eq("1");
        db.push((name, is_allergen, is_agricultural));
    }

    db
}

pub fn lookup_agricultural(name: &str) -> bool {
    for entry in food_db_full() {
        if entry.0.as_str() == name {
            return entry.2; // Return agricultural status
        }
    }
    true // Default to agricultural if not found
}
